### ISSUE TITLE
Confirm not only "working" but also "not affected" results

### ISSUE THREAD

**Issue by vielmetti** [lgeek/spec_poc_arm#1]
It would be useful to have a table in the README of systems known to be affected by this exploit, as well as also systems that are not affected.

**Comment by vielmetti** [comment]
On the Cavium ThunderX "Packet Type 2A" systems, running this exploit results in the message:
```
# ./dump_sys_regs 
Unreliable access timing
```

**Comment by lgeek** [comment]
Hi. Whether a system is vulnerable is down to the CPU core implementation. The specific SoC or platform is irrelevant. ARM published their list of vulnerable cores [here](https://developer.arm.com/support/security-update). For the variant implemented here (3a), those are Cortex-A15 (but that's an old 32-bit core), Cortex-A57 and Cortex-A72. From the cores implemented by other companies, I've tested APM X-Gene2 and it appears to be safe.

Cavium ThunderX is in-order as far as I know, so it should be safe. But there seems to be a problem with the software timer I've implemented - possibly because of the higher cache coherence latency in such a big multicore. It would be interesting if you could add a printf to the inner loop in `measure_latency()` to print the value of `ns`.

**Comment by vielmetti** [comment]
Here's the `ns` values for a few runs on ThunderX.

```
root@ed-2a-bcc-llvm:/home/src/github.com/lgeek/spec_poc_arm# ./dump_sys_regs 2>&1 | sort | uniq -c | sort -n      1 Unreliable access timing
     12 latency 1
     19 latency 2
    269 latency 0
root@ed-2a-bcc-llvm:/home/src/github.com/lgeek/spec_poc_arm# ./dump_sys_regs 2>&1 | sort | uniq -c | sort -n      1 latency 2
      1 Unreliable access timing
      6 latency 1
    293 latency 0
root@ed-2a-bcc-llvm:/home/src/github.com/lgeek/spec_poc_arm# ./dump_sys_regs 2>&1 | sort | uniq -c | sort -n      1 latency 4
      1 Unreliable access timing
      4 latency 2
     12 latency 1
    283 latency 0
root@ed-2a-bcc-llvm:/home/src/github.com/lgeek/spec_poc_arm# ./dump_sys_regs 2>&1 | sort | uniq -c | sort -n      1 Unreliable access timing
      5 latency 1
     14 latency 2
    281 latency 0
```

**Comment by lgeek** [comment]
Thanks. What's the distribution of values for the other iterations? If most are very low (under 5 for example), then the timer is simply too slow. If there's a lot of noise, then the system is probably too busy with other tasks.

**Comment by vielmetti** [comment]
The slowest result I was able to get was a single "latency 8" and a few "latency 5"'s. The system is otherwise idle.

**Comment by lgeek** [comment]
Hmm, that's a bit

**Comment by lgeek** [comment]
I've added a table showing the vulnerable implementations.

That seems a bit noisy for an idle system. You could try pinning the process to two specific cores (e.g. `taskset 3 ./dump_sys_regs`. If that doesn't work either, then you could try hard coding the value of `miss_min` - maybe to 4. But on an in-order implementation, you'll just get irrelevant mostly *0x0 (dynamic?)* results.

**Comment by vielmetti** [comment]
When I hard-code `miss_min` to 4, I get a series of results on ThunderX that look like

```
VBAR_EL1            : 0xffffffffffffffff 
VBAR_EL12           : 0xffffffffffffffff 
VBAR_EL2            : 0xffffffffffffffff 
VBAR_EL3            : 0xffffffffffffffff 
VMPIDR_EL2          : 0xffffffffffffffff 
VPIDR_EL2           : 0xffffffffffffffff 
```

**Comment by lgeek** [comment]
That's interesting, that would seem to indicate it's getting consistent cache hits in the probe array, which shouldn't happen. Is the value of `TPIDRRO_EL0` or other EL0-accessible registers all ones as well?

**Comment by vielmetti** [comment]
```
TPIDRRO_EL0         : 0xffffffffffffffff 
```

**Comment by jjones-cavium** [comment]
When I run this on _mumble_, with `miss_min` set to 4 and printing of latency, I get consistent reads of 0s, except for four registers:
```
$ taskset 3 ./dump_sys_regs | awk '$3 !~ /0x0/' | grep -v latency
CTR_EL0             : 0x8444c004
CNTFRQ_EL0          : 0xbebc200
CNTVCT_EL0          : 0x2e087803772d8 (dynamic?)
TPIDR_EL0           : 0xffff49ea2d90
```

**Comment by lgeek** [comment]
My bad, I've misread *slowest result I was able to get* as *the fastest* (because that's what `measure_latency()` is looking for: the fastest access on a cache miss) and therefore a `miss_min` of 4 is too high.

Meanwhile, I've tested this on a ThunderX machine and I can confirm that the software timer is running a bit too slow for reliable timing - as I've mentioned above, I think that's because cache coherence has high latency on this SoC. In any case, as expected, the machine doesn't seem to be vulnerable. For completeness, it would be useful to try and induce a stall by means other than a cache miss, in case this implementation has sufficient speculative capabilities to execute our code but has a blocking cache. That would be quite bizarre and unlikely, so I personally won't bother.

I'm closing this issue because I've addressed the original request and I don't consider the timing error worth addressing if it only affects systems that are not vulnerable. However, if someone runs into it consistently on a system that should be vulnerable, please reopen this issue - there are other timing techniques which can be used.

**Comment by lgeek** [comment]
@jjones-cavium Sorry, I didn't get to see your comment because I was writing mine at the same time. That's the expected output for a machine that's not vulnerable - more specifically it has enough speculative execution capabilities to attempt to execute the MRS, but it checks the permissions before using the output value. Those 4 registers are supposed to be readable from EL0. If you can tells us what core *mumble* :-) is using, I can add it as not vulnerable to the readme.

**Comment by jjones-cavium** [comment]
Thanks. I need to get clearance from my management, but this was for a core we determined was not vulnerable.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
